config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :channels 
  resources :subjects 
  resources :forums do 
  resources :replies 
end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'
  get '/home' => 'static_pages#home'
  get '/profile' => 'static_pages#profile'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'


  devise_for :users, controllers: {registrations: 'registrations'}
end

app/models/forum.rb
class Forum < ApplicationRecord

  belongs_to :subject
  belongs_to :user
  has_many :replies, dependent: :destroy # if forum is destroyed so are the replies

  validates :title, :content, presence: true # validates that their is content to reply

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  before_action :find_subjects, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /discussions
  # GET /discussions.json
  def index
    @forums = Forum.all.order('created_at desc')
    @subjects = Subject.all.order('created_at desc')
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
     @forums = Forum.all.order('created_at desc')
    @subjects = Subject.all.order('created_at desc')
  end

  # GET /discussions/new
  def new
    @forum = current_user.forums.build
  end

  # GET /discussions/1/edit
  def edit
  end

  def search
    
     st = "%#{params[:q]}%"
     @forums = Forum.where("title like ?", st).or(Forum.where("content like ?", st))
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @forum = current_user.forums.build(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    def find_subjects
      @subjects = Subject.all.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title, :content, :subject_id)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= simple_form_for(@forum) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :title, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, required: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Subject</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :subject_id, collection:@subjects.map { |s| [s.subject, s.id] }, prompt: "Select subject" %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class:"button is-info" %>
    </div>
  </div>

<% end %>

app/views/forums/_sidebar.html.erb
<div class="column is-3 is-offset-1">
  <h3 class="title is-5 has-text-grey-light">Subjects</h3>

  <ul class="list">
    <% @subjects.each do |s| %>
    <li><%= link_to s.subject, s %></li>
    <% end %>
  </ul>

  <br/>

  

</div>

app/views/forums/edit.html.erb
<h1 class="title is-3">Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<div class="columns">
  <%= render 'shared/forums' %>
  <%= render 'sidebar' %>
</div>

app/views/forums/new.html.erb
<h1 class="title is-size-3">New Forum Post</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/forums/search.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-three-quarters">
    <% if @forums.length == 0  %>

<h2>No results were found to match your search</h2>
<% end %>
</div>
</div>
<div class="columns is-mobile is-centered ">
  <div class="column is-three-quarters ">
      <% @forums.each do |forum| %>
     
       <h1><strong><%= forum.title %></strong></h1>
       <p> <%= truncate(forum.content, length: 540) %></p>
       <br />
         <%= link_to 'View',  forum, :class => "button", :role => "button" %>
         <hr>
              
  <% end %>
<br />

  </div>
</div>

app/views/forums/show.html.erb
<div class="columns">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey forum-title"><%= @forum.title %></h1>
    <h3 class="subtitle is-5 has-text-black-lighter">by <%= @forum.user.username %> in <%= link_to @forum.subject.subject, @forum.subject %></h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <%# if forum_author(@forum) %>
        <div class="buttons">
            <%= link_to 'Edit Forum', edit_forum_path(@forum), class:'button'%>
            <%= link_to 'Delete', forum_path(@forum), method: :delete, data: { confirm: "Delete forum?" }, class:'button' %>
        </div>
        <%# end %>
      </div>
    </div>
    <div class="content"><%= markdown(@forum.content) %></div>

    <h2 class="subtitle is-5 has-text-grey"><%= @forum.replies.count %> Replies</h2>

    <div id="forum-replies">
      <%= render @forum.replies %>
    </div>

    <hr />

    <h3 class="subtitle is-3 has-text-grey">Leave a reply</h3>
    <% if user_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
    <p>To reply you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>

  </div>

  <%= render 'sidebar' %>

</div>