config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :channels 
  resources :subjects 
  resources :forums do 
  resources :replies 
end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'
  get '/home' => 'static_pages#home'
  get '/profile' => 'static_pages#profile'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'


  devise_for :users, controllers: {registrations: 'registrations'}
end

app/models/college.rb
class College < ApplicationRecord
	
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:college)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= simple_form_for(@college) do |f| %>
  <%= f.error_notification %>

 <div class="field">
   <div class="control">
     <%= f.input :college, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
   </div>
 </div>

 <%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.college %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>College:</strong>
  <%= @college.college %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>