config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :channels 
  resources :subjects 
  resources :forums do 
  resources :replies 
end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'
  get '/home' => 'static_pages#home'
  get '/profile' => 'static_pages#profile'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'


  devise_for :users, controllers: {registrations: 'registrations'}
end

app/views/layouts/_search.html.erb
<div class="search">
	<div>
	
<%= form_tag("/search", :method => "post") do %>

<div class="field has-addons">
<%= text_field_tag(:q, "", :class => "input is-medium-2 ") %>

<%= submit_tag("Search", :class => "button is-info") %>
</div>
<% end %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alumni Ireland</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <section class="hero is-smallx2 is-primary"> <div class="hero-body"> <div class="container has-text-centered"> <h1 class="title has-text-white">Welcome to Alumni Ireland</h1>
     <%=render 'layouts/search'%></div> </div> </section>


    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Alumni Ireland</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">

         <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Home', home_path, class:"navbar-item" %>
            </div>
          </div>

          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Members', members_path, class:"navbar-item" %>
            </div>
          </div>

          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Forums', forums_path, class:"navbar-item" %>
            </div>
          </div>

         <!-- <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Colleges', colleges_path, class:"navbar-item" %>
            </div>
          </div>

          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Channels', channels_path, class:"navbar-item" %>
            </div>
          </div>


          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'Subjects', subjects_path, class:"navbar-item" %>
            </div>
          </div>
        -->
         


          <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Status', profiles_path, class:"button is-info" %>
            </div>
          </div>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Post', new_forum_path, class:"button is-info" %>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
               <%= link_to current_user.username, profiles_path, class:"navbar-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class:"navbar-item" %>
               <%= link_to "My posts", '#', class:"navbar-item" %>
             
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
         <% else %>
         <div class="navbar-item">
          <div class="field is-grouped">

           
            <p class="control">
              <%= link_to "Members", '#', class: "button is-light"%>
            </p>
            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-light"%>
            </p>

            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class: "button is-light" %>
            </p>
          </div>
          </div>
          <% end %>

        </div>
    </div>
  </nav>

<section class="section">
  <div class="container">
    <%= yield %>
  </div>
</section>

  </body>
</html>